config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :robots
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/robot.rb
class Robot < ApplicationRecord
	include ActiveModel::Model

  attr_accessor :size_grid, :max_x, :max_y, :x, :y, :f, :commands, :report

  def initialize(params={})
    @x = params[:x].try(:to_i)
    @y = params[:y].try(:to_i)
    @f = params[:f] || ""
    @size_grid = sanitize_size(params[:size_grid])
    @max_x, @max_y = @size_grid.split('x').map(&:to_i)
    @commands = params[:commands] || ""
    @report = nil
  end

  def execute_commands!
    return unless check_if_robot_is_placed?

    commands = @commands.gsub(/\r\n/,' ')
    commands = commands.to_s.upcase.split(' ')
    commands.each_with_index do |command, index|
      placing_initial_coordinates(commands[index+1]) if command == "PLACE"
      case command
      when 'MOVE'
        move_into_new_position
      when 'LEFT'
        change_direction('LEFT')
      when 'RIGHT'
        change_direction('RIGHT')
      when 'REPORT'
        generate_report
        break
      end if self.isExists?
    end
    warning_message
  end

  def isExists?
    @x && @y && !@f.empty?
  end

  private

    def check_if_robot_is_placed?
      if !self.isExists? && !@commands.include?("PLACE")
        @x, @y = ""
        errors.add(:warning, 'You might need to place the robot first!')
        return false
      end
      return true
    end

    def placing_initial_coordinates(args)
      @x, @y, @f = args.split(',')
      @x = @x.to_i
      @y = @y.to_i
    end

    def move_into_new_position
      case @f
      when 'NORTH'
        @y = @y+1 unless (@y+1) > (@max_y - 1)
      when 'WEST'
        @x = @x-1 unless (@x-1) < 0
      when 'SOUTH'
        @y = @y-1 unless (@y-1) < 0
      when 'EAST'
        @x = @x+1 unless (@x+1) > (@max_x -1)
      end
    end

    def change_direction(direction)
      case @f
      when 'NORTH'
        @f = direction.eql?('LEFT') ? 'WEST' : 'EAST'
      when 'WEST'
        @f = direction.eql?('LEFT') ? 'SOUTH' : 'NORTH'
      when 'SOUTH'
        @f = direction.eql?('LEFT') ? 'EAST' : 'WEST'
      when 'EAST'
        @f = direction.eql?('LEFT') ? 'NORTH' : 'SOUTH'
      end
    end

    def generate_report
      @report = "#{@x},#{@y},#{@f}"
    end

    def warning_message
      errors.add(:warning, 'Wrong direction! your robot is about to fall of..') unless check_warning
    end

    def check_warning
      case @f
      when "NORTH"
        return false
      when "WEST"
        return false if @x==0
      when "EAST"
        return false if @x==@max_x-1
      end if @y==@max_y-1

      case @f
      when "SOUTH"
        return false
      when "WEST"
        return false if @x==0
      when "EAST"
        return false if @x==@max_x-1
      end if @y==0

      return false if @x==@max_x-1 && @f == "EAST"
      return false if @x==0 && @f == "WEST"

      return true
    end

    def sanitize_size(size_grid)
      size_grid.to_s.match(/\dx\d/) ? size_grid : "5x5"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  protect_from_forgery with: :exception
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController

	def new
		@robot = Robot.new
	end
	
	def create
		@robot = Robot.new(params[:robot])
    @robot.execute_commands!
    render :new
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RobotApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/robots/_form.html.erb
<%= form_for(@robot, url: robots_path) do |f| %>
  <% if @robot.errors.any? %>
    <ul>
    <% @robot.errors.full_messages.each do |msg| %>
      <li><b style="color:orange"><%= msg %></b></li>
  <% end %>
  </ul>
  <% end %>
  <table>
    <tr>
      <td colspan="2">
        <div class="field">
          <%= f.label :size_grid %>
          <%= f.text_field :size_grid, placeholder: 'Size Grid', style: "width:50px" %>
          <i>Type size of the Grid default: 5x5</i>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <%= f.label :commands %><br/>
          <%= f.text_area :commands, placeholder: 'Commands', style: "width:350px;height:150px" %>
          <p style="width:400px"><i>Type commands available: [ PLACE X,Y,( NORTH | WEST | SOUTH | EAST ) | MOVE | LEFT | RIGHT | REPORT ] - whitespace delimited</i></p>
          <b><%= "Output: #{@robot.report}" if @robot.report %></b>
        </div>
      </td>
      <td>
        <p>
          <b>Shortcut for navigations:</b><br/>
          <b>Ctrl+Shift+N : MOVE NORTH</b><br/>
          <b>Ctrl+Shift+W : MOVE WEST</b><br/>
          <b>Ctrl+Shift+S : MOVE SOUTH</b><br/>
          <b>Ctrl+Shift+E : MOVE EAST</b><br/>
        </p>
        <%= f.hidden_field :max_x %>
        <%= f.hidden_field :max_y %>
        <%= f.hidden_field :x %>
        <%= f.hidden_field :y %>
        <%= f.hidden_field :f %>
      </td>
    </tr>
  </table>

  <div class="field">
    <%= f.submit 'Post Commands' %>
  </div>
<% end %>

app/views/robots/new.html.erb
<h1>Toy Robot Simulator</h1>

<%= render 'form' %>

<canvas id="myCanvas" width="<%= "#{@robot.max_x}51" %>" height="<%= "#{@robot.max_y}51" %>">Your web browser does not supports HTML5!</canvas>